### ISSUE TITLE
Formatting errors: 01. Introduction to Julia

### ISSUE THREAD

**Issue by longemen3000** [dpsanders/6.S083#1]
**page 12:**
Functions behave differently for different types: `julia 3 * 3` - julia should be in a new line
**page 13:**
function word repeated
**page 23:**
factorial function lacks formatting
**page 30:**
methods ()show methods
**page 33:**
import`ing`

**Comment by dpsanders** [comment]
Thanks and sorry I didn't notice this at the time.
